---
########################################
###           DISCORD BOT            ###
###       CONFIGURATION FILE         ###
########################################


########################
# GENERAL BOT SETTINGS #
########################

# The bot token that the bot should use to log in
botToken: "insert bot token"

# The name of the bot (warning: if the name is too common, the bot will not start)
botName: "Harry"

# The webhook url

# The prefix that the bot commands should use
commandPrefix: "/"

# How long in seconds should the bot wait before removing its messages
msgDeleteTime: 30

# How long is minutes should the bot wait before deleting empty custom channels
customChannelDeleteTime: 10


###############################
# MY SQL USERS DATABASE CREDS #
###############################
usersDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


##############################
# MY SQL PLAN DATABASE CREDS #
##############################
planDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


##############################
# MY SQL BANS DATABASE CREDS #
##############################
bansDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


#################################
# MY SQL XENFORO DATABASE CREDS #
#################################
xenDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


########################
# REDIS DATABASE CREDS #
########################
redisDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


#########################
#   MINESTAT SETTINGS   #
#########################
mineStatSettings:

  # The IP of the server Minestat should refresh (VPS can't ping mc-gtm.net for some reason)
  serverIp: "insert ip"

  # The port of the server Minestat should refresh (Will almost always be 25565)
  serverPort: 25566

  # How often in seconds should the bot refresh the server's player count?
  refreshFrequency: 361


#########################
#   RAID MODE SETTINGS  #
#########################

raidmodeSettings:

  # The number of players that need to join in the below configured time to active raid mode
  raidModePlayers: 4

  # The time peroid over which raid mode checks players in seconds
  raidModeTime: 30

  # When raid mode is *automatically* triggered, how long after the last bot is detected should it disable (in minutes)
  raidModeDisable: 1

  # If raid mode is active, and a new player joins with in this many seconds of the previous player, punish them because they are bot (this time can't be larger then raidModeTime)
  raidModePunishTime: 15

  # How much time should we give new players to accept the rules before we kick them in minutes (forcing them to react to a msg also prevents basic bots)
  raidModeTimeToAccept: 15

  # What should we do to the players detected as bots? (Options: KICK, BAN, NOTIFY)
  raidModePunishType: "KICK"

  # What should the bot message the player on executing the punishment. You may use discord formating. Use \n for linebreaks. (Note: This only works for bans / kicks)
  raidModeMessage: "**You were kicked from the discord because you were detected being a bot! If you believe this was an error, simply rejoin! **"

################################
#     RANK SETTINGS NAMES      #
################################

# The bot uses the following role ids get the role for each rank.
# Simply right click the discord role and select "copy id" to get the id.

rankSettings:
  manager: -1
  developer: -1
  admin: -1
  builder: -1
  srMod: -1
  mod: -1
  helper: -1
  buildTeam: -1
  youtuber: -1
  supreme: -1
  sponsor: -1
  elite: -1
  premium: -1
  vip: -1
  noRank: -1
  unverified: -1
